
# # .PHONY: makemigrations migrate run create_superuser
#
# makemigrations:
#     python manage.py makemigrations
# migrate:
#     python manage.py migrate
# run:
#     python manage.py runserver 8000
#
# create_superuser:
#     python manage.py createsuperuser
#
# up:
#     docker-compose up -d
#
# up_build:
#     docker-compose down
#     docker-compose up --build -d
#
# down:
#     docker-compose down
#
# start:
#     docker-compose start
#
# stop:
#     docker-compose stop

#.PHONY: makemigrations migrate run create_superuser

makemigrations:
    python manage.py makemigrations

migrate:
    python manage.py migrate

run:
    python manage.py runserver 8000

create_superuser:
    python manage.py createsuperuser

up:
    docker-compose up -d

up_build:
    docker-compose down
    docker-compose up --build -d

down:
    docker-compose down

start:
    docker-compose start

stop:
    docker-compose stop
