"""
Django settings for Delivery_Project project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
import json
from pathlib import Path
# from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# provide environment file path to configure the environment variables
# dot_env_path = os.path.join(BASE_DIR, '.env')
# # print(dot_env_path)
# load_dotenv(dot_env_path)

# CONNECTION_STRING = os.getenv('CONNECTION_STRING')
# print(CONNECTION_STRING)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = ''

##### SECRET_KEY = os.getenv('appcredsJson')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.getenv('DEBUG', False)

ALLOWED_HOSTS = ['*', '49.43.218.50']

# Application definition

with open('C:/Zaperr/BE/appcreds_json.json') as appcreds_file:
    appcreds = json.load(appcreds_file)


'''with open(os.path.join(BASE_DIR, 'appcreds_json.json')) as appcreds_file:
    appcreds = json.load(appcreds_file)
'''
'''# Load credentials from appcreds_json.json
appcreds_path = os.getenv('appcredsJson')
with open(appcreds_path) as appcreds_file:
    appcreds = json.load(appcreds_file)
'''
CONNECTION_STRING = appcreds.get("CONNECTION_STRING")
SECRET_KEY = appcreds.get("SECRET_KEY")
QUEUE_LENGTH = appcreds.get("Queue_Length")
BUILD_ENV = appcreds.get("buildEnv")
DEBUG = appcreds.get("DEBUG") #True
NOTIFICATION_DURATION = appcreds.get("Notification_Duration")
# print(DEBUG)
# print(f'notification: {NOTIFICATION_DURATION}')



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Delivery_App',
    'rest_framework',
    'corsheaders',
    # 'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #adding additional
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'Delivery_Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Delivery_Project.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    # "http://<your-react-ip>:3000",  # Replace with the IP of the React app's laptop
    # "http://192.168.29.34:3000",  # Replace with the IP of the React app's laptop
    "http://115.97.180.11:3000",  # Replace with the IP of the React app's laptop
]

CORS_ALLOW_ALL_ORIGINS = True

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'cartservice',  # Replace with your MongoDB database name
#         'HOST': 'localhost',            # Assuming MongoDB is running locally
#         'PORT': 27017,                  # MongoDB default port
#         'USER': 'srk_cluster0',        # Replace with your MongoDB username (if applicable)
#         'PASSWORD': '7N9u4iBRwA6BFOsK',    # Replace with your MongoDB password (if applicable)
#         'AUTH_SOURCE': 'admin',         # Specify the authentication database
#     }
# }
#

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
